### ISSUE TITLE
Npm package doesn't contain all files

### ISSUE THREAD

**Issue by danielchatfield** [sindresorhus/generator-nm#3]
The package published to npm does not contain all the files.

The contents of templates is:

 - _package.json 
 - index.js
 - license
 - readme.md
 - test.js

**Comment by danielchatfield** [comment]
Hmm, the files are missing even when I install direct from github which is strange.

```
/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:580
    throw e;
          ^
AssertionError: /usr/local/lib/node_modules/generator-nm/app/templates/.gitignore doesn't exist
    at EditionInterface.module.exports [as read] (/usr/local/lib/node_modules/generator-nm/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/read.js:13:3)
    at template (/usr/local/lib/node_modules/generator-nm/node_modules/yeoman-generator/lib/actions/actions.js:191:34)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-nm/app/index.js:47:9)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-nm/node_modules/yeoman-generator/lib/base.js:221:7)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:69:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1955:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1892:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:568:29)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:4886:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1892:14)
```

**Comment by eduardoroyer** [comment]
+1

**Comment by kevva** [comment]
Either this is a npm issue or @sindresorhus didn't publish with all files.

**Comment by arthurvr** [comment]
Yup. Looks like not all files were published.

**Comment by eduardoroyer** [comment]
yes, I'm doing this right now.

**Comment by kevva** [comment]
I just tried installing from github and I got all the files.

**Comment by eduardoroyer** [comment]
That's it

**Comment by sindresorhus** [comment]
@eduardoroyer 

> What npm version etc are you running?

**Comment by eduardoroyer** [comment]
@sindresorhus I'm running npm 1.4.28 and node v0.10.36

**Comment by kevva** [comment]
@eduardoroyer, you should really update npm. `npm install --global npm@latest`.

@sindresorhus, I ran this with 2.7.0 and it failed anyway. I think npm ignores `.gitignore` by default.
